[package]
name = "sqlite-functions"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = { version = "0.4", features = [ "serde-json" ] }  # '-' not '_'
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
