name: build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up ARM64 chroot environment
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static debootstrap
          sudo debootstrap --arch=arm64 --variant=minbase focal /arm64-chroot
          sudo cp /usr/bin/qemu-aarch64-static /arm64-chroot/usr/bin/

      - name: Install build dependencies in chroot
        run: |
          sudo mkdir chroot /arm64-chroot/build
          sudo cp -r . /arm64-chroot/build
          sudo ./scripts/setupChroot.sh
          sudo chroot arm64-chroot /build/scripts/installDeps.sh
